DROP PROCEDURE IF EXISTS CREATE_TABLE;
CREATE PROCEDURE CREATE_TABLE()
BEGIN

    IF NOT EXISTS
        (SELECT 1 FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_SCHEMA = DATABASE() AND TABLE_NAME = 'USER')
    THEN
        CREATE TABLE USER_AUTH (
              ID                 INTEGER         NOT NULL AUTO_INCREMENT COMMENT '主键ID',
              PHONE              INTEGER(11)     NOT NULL COMMENT '手机号',
              PASSWORD           VARCHAR(20)     NULL DEFAULT '' COMMENT '密码',
              WX_OPENID			 VARCHAR(200)    NULL DEFAULT '' COMMENT '微信的openid',
              CREATE_TIME        TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
              REVISE_TIME        TIMESTAMP       NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '修改时间',
              PRIMARY KEY (ID),
              UNIQUE KEY USER_AUTH(PHONE)
        ) COMMENT '用户表';

    END IF;

END;
CALL CREATE_TABLE();
DROP PROCEDURE IF EXISTS CREATE_TABLE;
